apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spring-producer-deployment
spec:
  selector:
    matchLabels: 
      app: spring-producer-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-producer-app
    spec:
      containers:
      - image: eskaronea/spring_producer:latest
        name: greeting-producer
        ports:
         - containerPort: 8080
status: {}
