server.port: 80
management.server.port: 9001
management.server.address: 127.0.0.1
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-headless:9092
        #binder:
        #  brokers: localhost:9092
      bindings:
        greetings-out:
          destination: greetings
          contentType: application/json  
